#!/bin/sh

brew install \
  atool \
  brave-browser \
  btop \
  cmake \
  dua-cli \
  keychain \
  firefox \
  gh \
  git-delta \
  gpg2 \
  htop \
  kitty \
  libvips \
  micromamba \
  pnpm \
  pinentry-mac \
  ninja \
  nvim \
  nvm \
  ranger \
  tig \
  rust \
  rustup \
  starship \
  tmux \
  tmux-mem-cpu-load \
  visual-studio-code \
  wasmtime \
  wezterm \
  zsh-autosuggestions \
  zsh-syntax-highlighting
