#!/bin/sh

apt-get install \
  atool \
  build-essential \
  btop \
  ccache \
  clang \
  cppcheck \
  cgdb \
  universal-ctags \
  curl \
  fd-find \
  fonts-firacode \
  keychain \
  gh \
  git \
  git-delta \
  gnupg2 \
  fonts-inconsolata \
  libeigen3-dev \
  libexpat1-dev \
  libfftw3-dev \
  libhdf5-dev \
  libjpeg-dev \
  libpng-dev \
  libtiff-dev \
  libssl-dev \
  nvtop \
  ncurses-dev \
  ninja-build \
  pdfgrep \
  pinentry-curses \
  python3-dev \
  pylint \
  pavucontrol \
  ranger \
  tig \
  tmux \
  tree \
  valgrind \
  neovim \
  zsh \
  zsh-autosuggestions \
  zsh-syntax-highlighting

update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
update-alternatives --config vi
update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
update-alternatives --config vim
update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
update-alternatives --config editor
