#!/bin/sh

emerge \
  atool \
  awesome \
  bash-completion \
  ccache \
  cdargs \
  clang \
  cppcheck \
  cgdb \
  ctags \
  docker \
  eselect-bashcomp \
  keychain \
  flake8 \
  fortune-mod-all \
  google-talkplugin \
  inconsolata \
  mosh \
  nemiver \
  dev-util/ninja \
  pdfgrep \
  pylint \
  pyqtgraph \
  pavucontrol \
  qtile \
  ranger \
  rxvt-unicode \
  subversion \
  the_silver_searcher \
  tig \
  youcompleteme \
  valgrind \
  x11-misc/xclip \
  zsh \
  zsh-completion \
  zsh-completions \
  zsh-syntax-highlighting

eselect bashcomp enable --global \
  bash-builtins \
  cmake \
  configure \
  docker \
  eix \
  gdb \
  git \
  git-prompt \
  gpg2 \
  imagemagick \
  make \
  ninja \
  python \
  ssh \
  tig \
  tmux \
  valgrind \
  vim \
  xmodmap
