#!/usr/bin/env bash

cd ~
for config in .bashrc \
  .bash_completion.d \
  .bash_profile \
  .gitconfig \
  .gitignore_global \
  .git_prompt.zsh \
  .gnupg \
  .inputrc \
  .tern-project \
  .tmux.conf \
  .tmux \
  .p10k.zsh \
  .vim \
  .vimrc \
  .wgetrc \
  .Xdefaults \
  .ycm_extra_conf.py \
  .zshrc
  do
  if test -f $config -a ! -L $config; then
    mv $config ${config}.old
  fi
  if test ! -e $config; then
    ln -s ~/.config/dotfiles/$config
  fi
done

cd ~/.config
for config in awesome \
  qtile \
  nvim \
  kitty
  do
  if test ! -d $config; then
    ln -s ~/.config/dotfiles/.config/$config
  fi
done

if test ! -e .tmux.local.conf; then
  cp ~/.config/dotfiles/.tmux.local.conf .
fi

cd ~/.vim/bundle/vimproc.vim/
make

mkdir -p ~/.local/share/fonts
#if [[ ! -e "Inconsolata for Powerline Nerd Font Complete Mono Windows Compatible.otf" ]]; then
  #cd ~/.local/share/fonts
  #curl -fLo "Inconsolata for Powerline Nerd Font Complete Mono Windows Compatible.otf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Inconsolata/complete/Inconsolata%20for%20Powerline%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.otf
  #fc-cache -f ~/.local/share/fonts
#fi
# deprecated location
if test ! -d ~/.fonts; then
  ln -s ~/.local/share/fonts ~/.fonts
fi
